title: Chengqiang Lin's Homepage
page-top-title: Chengqiang Lin
top-section-bg-text: Electronic Information
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
  - static/assets/background/background_2.jpeg
background-interval-ms: 7000
background-overlay: 0.3
copyright-text: '&copy; Chengqiang Lin 2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/colinoo00310
license-link:
  text: License
  href: https://github.com/colinoo00310/colinoo00310.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: Chengqiang Lin&ensp;|&ensp;林成强
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: certificates
    nav: CERTIFICATES
    title: CERTIFICATES
    icon: bi-patch-check-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
